---
default_language_version:
    python: python3

exclude: |
    (?x)^(
      build/.*|
      tests/.*
    )$

default_stages: [commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-added-large-files
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: check-ast
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: destroyed-symlinks
          - id: requirements-txt-fixer
    - repo: local
      hooks:
          - id: gem5-style-checker
            name: gem5 style checker
            entry: util/git-pre-commit.py
            always_run: true
            exclude: .*
            language: system
            description: The gem5 style checker hook.
          - id: gem5-commit-msg-checker
            name: gem5 commit msg checker
            entry: util/git-commit-msg
            language: system
            stages: [commit-msg]
            description: The gem5 commit message checker hook.
