---
default_language_version:
    python: python3

exclude: |
    (?x)^(
      build/.*|
      tests/.*
    )$

default_stages: [commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-added-large-files
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: check-ast
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: destroyed-symlinks
          - id: requirements-txt-fixer
    - repo: local
      hooks:
          - id: clang-format
            name: clang-format
            entry: clang-format
            files: \.(cpp|hpp|h|tcc|tpp|cc|hh|yy|ll)$
            always_run: true
            description: clang-format hook
            language: system
          - id: yapf
            name: yapf
            entry: yapf
            files: \.(py)$
            always_run: true
            description: yapf hook
            language: python
